### ISSUE TITLE
 弱弱问一下这个的后台程序有么。。。

### ISSUE THREAD

**Issue by a22349** [fanfanSky/merchant_uni-app#1]
多谢了

**Comment by LiCiMaKaKa** [comment]
这个用什么命令运行呀

**Comment by LiCiMaKaKa** [comment]
想试一下能不能运行起来，不知道怎么运行

**Comment by fanfanSky** [comment]
> 想试一下能不能运行起来，不知道怎么运行

hbuilderx运行到浏览器或者手机都可以

**Comment by fanfanSky** [comment]
> 多谢了

后台程序是java写的，我也不知道还在不在

**Comment by fanfanSky** [comment]
> > 想试一下能不能运行起来，不知道怎么运行
> 
> hbuilderx运行到浏览器或者手机都可以

**Comment by LiCiMaKaKa** [comment]
下载下来解压缩不了了，不知道为什么


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanfanSky/merchant_uni-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月24日(星期一) 晚上11:48
***@***.***&gt;;
抄送:&nbsp;"Je voulais te ***@***.******@***.***&gt;;
主题:&nbsp;Re: [fanfanSky/merchant_uni-app]  弱弱问一下这个的后台程序有么。。。 (#1)





   
想试一下能不能运行起来，不知道怎么运行
  
hbuilderx运行到浏览器或者手机都可以
